### PR TITLE
Bump build number

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by dnadeau4** [comment]
I got the same `BlockingIOError` issue on my mac OSX.  This happens in the test section.  I am not sure why. ..

```
bin/mpiexec.hydra

  filetype: EXECUTE

  rpath: /Users/travis/miniconda3/conda-bld/mpich_1506349785019/_t_env/lib:/Users/travis/miniconda3/conda-bld/mpich_1506349785019/_t_env/Traceback (most recent call last):

  File "/Users/travis/miniconda3/bin/conda-inspect", line 6, in <module>

    sys.exit(conda_build.cli.main_inspect.main())

  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_inspect.py", line 190, in main

    return execute(sys.argv[1:])

  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_inspect.py", line 181, in execute

    print(api.inspect_objects(args.packages, prefix=get_prefix(args), groupby=args.groupby))

BlockingIOError: [Errno 35] write could not complete without blocking

lib:@loader_path/../lib/
```

**Comment by minrk** [comment]
I believe the failure is due to the O_NONBLOCK issue in mpich that's caused various issues in the past. Not sure why it started affecting this case.

**Comment by dalcinl** [comment]
Maybe because the `conda inspect` cases are run after previous tests using `mpiexec`?

**Comment by minrk** [comment]
Yes. Any random process that writes to stdout after `mpiexec` is likely to fail. I decided to look into this a bit more and opened a PR against mpich that fixes it (https://github.com/pmodels/mpich/pull/2755), so we'll see what they say about that. We can vendor the patch once it's accepted because this has caused problems for loads of packages that depend on mpich.

**Pull request merged**
