### PR TITLE
BUG make sure external variant has same run deps

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR is the same as https://github.com/conda-forge/openmpi-feedstock/pull/156 but for mpich to solve the same issue.

xref: https://github.com/conda-forge/openmpi-feedstock/pull/156
xref: #95

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge/mpich this one is ready for review!

**Comment by dalcinl** [comment]
As @minrk said elsewhere, if this is ultimately a temporary fix to help the solver until a more fundamental solution is found, then I'm OK with it.

**Review by dalcinl — APPROVED** [review]

**Pull request merged**
