### PR TITLE
recipe: Use a single-line definition for version_url

### PR DESCRIPTION
**Pull request by dalcinl**
cf. regro/cf-scripts#1784 regro/cf-scripts#1785.

### CODE REVIEW

**Comment by dalcinl** [comment]
@jakirkham @beckermr Guys, I need a bit of help here. I've added the `[ci skip]` stanza in my commit message. Is there any other thing I should care about before merging this PR?

**Comment by beckermr** [comment]
Azure ignores CI skip on PRs but will respect it for actual feedstock builds. So I'd let the builds go to make sure they pass and then merge.

**Comment by jakirkham** [comment]
Yeah think this should be good to go

Thank you both! 🙏

**Comment by dalcinl** [comment]
Thanks for all the assistance.

PS: I'm wondering why the `automerge` label did not make it. Merging manually...

**Pull request merged**
