### PR TITLE
ENH add shim for external MPI

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR adds a shim for external MPI distributions per https://github.com/conda-forge/staged-recipes/pull/9536 and https://github.com/conda-forge/conda-forge.github.io/issues/860.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
OK @minrk @isuruf. Can you all take a look at this version of the shims? 

Given that `mpich` has an initiative around ABI compatibility, we might just merge this and pass on supporting `openmpi` for the time being.

**Comment by beckermr** [comment]
Bump here @conda-forge/mpich

**Comment by dalcinl** [comment]
@beckermr I have no idea about how this external MPI support is actually implemented, so I'm not qualified to review your changes. Do you want me to merge this one right away?

**Comment by beckermr** [comment]
Yes please @dalcinl! This one is ready to merge!

**Comment by minrk** [comment]
Let's merge this one, which will create the 3.3.1 build. If you can report back on how it is working for you, we can make sure that a few past versions get uploaded as well, if that seems useful.

One thing that may prove useful: a post-link script that verifies it can be found and is an appropriate version (e.g. checking for libmpi.so.12), rather than just an empty package.

**Comment by leofang** [comment]
@beckermr Two questions:
1. How to use the "external" feature if there's already an MPI library outside the conda env? Is it documented somewhere?
2. Could you propagate this change to openmpi-feedstock?

**Comment by beckermr** [comment]
Hmmmm. I bet I didn't write docs. Install the proper build with the feature and it should just work. 

We cannot so openmpi because the ABI stability there is pretty bad.

**Comment by beckermr** [comment]
Something like

```
conda install mpich==*=external_*
```

should be close to what you need.

**Comment by leofang** [comment]
Thanks, @beckermr!

> Hmmmm. I bet I didn't write docs. Install the proper build with the feature and it should just work.

I found there is a CF doc section on MPI: https://conda-forge.org/docs/maintainer/knowledge_base.html#message-passing-interface-mpi What's the right repo to submit a PR?

> We cannot so openmpi because the ABI stability there is pretty bad.

Oh...I know there's not ABI-compatibility guarantee in Open MPI, but I thought your earlier comment https://github.com/conda-forge/conda-forge.github.io/issues/860#issuecomment-530976401 suggested it's still doable. I probably parsed it wrong...

Still, couldn't we at least make it available for any downstream conda packages? I imagine something like this should work:
```
conda install openmpi=*=*external* mpi4py=*=*openmpi* h5py=*=*openmpi*
```
Since Open MPI and MPICH are mutually exclusive through the `mpi` meta package, it should be enough to avoid the ABI compatible issue, don't you think?

**Comment by beckermr** [comment]
Sorry I was not clear. openmpi is not abi compatible with itself. What we are doing here is compiling against one version of the libs (our mpich) and then linking code against another. openmpi may not work doing that. mpich has a much better chance.

**Comment by leofang** [comment]
> openmpi is not abi compatible with itself

I see. I was not aware of that. Thanks, Matt!

**Pull request merged**
