### PR TITLE
Update to mpich 3.4, using CH3 as default configuration

### PR DESCRIPTION
**Pull request by brianv0**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

z
mpich 3.4 uses CH4 device configuration by default, but we now need an OFI (http://libfabric.org) or UCX (http://openucx.org) library to build CH4. Rather than making a decision on that, I set the default back to CH3 for now.

### CODE REVIEW

**Comment by brianv0** [comment]
@conda-forge-admin, please rerender

**Comment by brianv0** [comment]
It seems config.sub/config.guess for (unfortunately vendored and adjustable by `configure`, json-c) needs to be patched for osx arm64.

**Comment by dalcinl** [comment]
@brianv0 Could you confirm whether this ready for merge?

**Comment by brianv0** [comment]
Yes it’s ready. The large number of lines changes is from patching _all_ config.sub and config.guess files (I opened an issue upstream about this)

**Comment by leofang** [comment]
Just curious, wouldn't it be safer if the patch were only applied to osx arm64?

**Comment by dalcinl** [comment]
> Just curious, wouldn't it be safer if the patch were only applied to osx arm64?

Perhaps. Are you thinking about adding the `# [osx and arm64]` selector to the patch?

**Comment by dalcinl** [comment]
@brianv0 How did you generate the patch? Did you run `./autogen.sh` on MPICH's git repo with updated autotools supporting macOS ARM64?

**Comment by leofang** [comment]
> > Just curious, wouldn't it be safer if the patch were only applied to osx arm64?
> 
> Perhaps. Are you thinking about adding the `# [osx and arm64]` selector to the patch?

Yap. Of course it is ok to leave as is if no one complains. Just wondering when reading the recipe here.

**Comment by leofang** [comment]
Friendly ping @brianv0, as we'll need a more robust way to generate the patch for `arm64`.

**Pull request merged**
