### PR TITLE
Add UCX support and some recipe updates

### PR DESCRIPTION
**Pull request by dalcinl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

xref https://github.com/conda-forge/openmpi-feedstock/issues/181
xref https://github.com/conda-forge/openmpi-feedstock/pull/184

### CODE REVIEW

**Comment by minrk** [comment]
Thanks for the recipe cleanup. Let's try to arrive on a plan for what to do about multiple device support so we can be consistent across providers in https://github.com/conda-forge/openmpi-feedstock/issues/181. If we land this, all 3 of openmpi, mpich, and mvapich will have ofi and ucx support, and all 3 will have taken different approaches with user-facing consequences for how to select implementations.

**Comment by dalcinl** [comment]
@j34ni Why your original PR did not add UCX for ppc64le?

**Comment by j34ni** [comment]
@dalcinl I don't remember, must have had issues building it, or missing dependencies at the time

**Comment by dalcinl** [comment]
Indeed, something as basic as running `mpichversion` segfaults. This would require further investigation.

**Review by minrk — APPROVED** [review]

**Comment by dalcinl** [comment]
@minrk So, what to do now? Remove from draft state, cross fingers, and merge?

**Comment by minrk** [comment]
yeah, I think so

**Pull request merged**
