### PR TITLE
run_exports

### PR DESCRIPTION
**Pull request by minrk**
Building against mpich 3.2.1 will have an automatic runtime dependency on mpich>=3.2.1,<3.3.0

### CODE REVIEW

**Comment by dalcinl** [comment]
Are you sure about this? MPICH's ABI is quite stable. On the other side, MPICH do not make new releases so often, so I guess this OK.

**Comment by minrk** [comment]
This is duplicating the same pinning most downstream packages are doing (`3.2.*` is equivalent to `>=3.2.0,<3.3.0`), so I think it should be fine.

The two ways we could relax this:

1. `min_pin='x.x'` would allow packages built against 3.2.1 to install with 3.2.0 (probably fine, and *exactly* the pinning we are using now with `3.2.*`) (I updated the PR to reflect this)
2. `max_pin='x'` would allow packages built against 3.2.x to run with 3.3.x (and 3.4.x, etc.). Does mpich guarantee ABI compatibility across minor versions?

**Comment by dalcinl** [comment]
I think ABI compatibility should be guaranteed on minor versions, however I'm fine with `3.2.*`.

**Comment by minrk** [comment]
Sounds good. We can try an experiment relaxing this later when there's another version.

**Pull request merged**
