### PR TITLE
Add --disable-opencl to configure

### PR DESCRIPTION
**Pull request by hhslepicka**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Ref. https://github.com/conda-forge/mpich-feedstock/issues/56#issuecomment-770416217

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
Travis-CI seems to be failing with an `out of space` error... it does not seem to be related to this PR... Is that normal?

**Comment by hhslepicka** [comment]
@conda-forge/mpich let's merge this

**Comment by hhslepicka** [comment]
Thank you, @dalcinl

**Comment by leofang** [comment]
@conda-forge/mpich This merge run failed, needs to be reset:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=272347&view=logs&j=19c5f193-32c3-5f7a-3606-03d7ec27c3e8

**Comment by dalcinl** [comment]
@leofang I've rerun the the failed builds.

**Comment by leofang** [comment]
Thanks @dalcinl! Looks good now.

**Pull request merged**
