### PR TITLE
4.0.0 is out

### PR DESCRIPTION
**Pull request by MarDiehl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by dalcinl** [comment]
@MarDiehl You need to add the following arguments to the configure invokation in `recipe/build-mpi.sh`:

```shell
./configure --prefix=$PREFIX \
            FCFLAGS=-fallow-argument-mismatch \
            FFLAGS=-fallow-argument-mismatch \
            ...
```

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
> @MarDiehl You need to add the following arguments to the configure invokation in `recipe/build-mpi.sh`:
> 
> ```shell
> ./configure --prefix=$PREFIX \
>             FCFLAGS=-fallow-argument-mismatch \
>             FFLAGS=-fallow-argument-mismatch \
>             ...
> ```

thanks! I'll see if I can get it to work also with `MPICHLIB_FFLAGS` and `MPICHLIB_FCFLAGS` to avoid polluting the flags in the compiler wrappers.

**Comment by MarDiehl** [comment]
@conda-forge-admin, please rerender

**Comment by MarDiehl** [comment]
I don't know why the `typeconda` variants don't honor the `MPICHLIB_xFLAGS` flags. But I don't even know what the difference for the both type flavors is, so I suggest that any of the maintainers takes over.

**Comment by dalcinl** [comment]
@MarDiehl Could you please set  `FCFLAGS` and `FFLAGS` in the configure invocation as I instructed before?. You may need these flags in all cases, otherwise the `mpifort` compiler wrapper may be unusable to compile Fortran MPI programs. Look like [Fedora](https://src.fedoraproject.org/rpms/mpich/blob/rawhide/f/mpich.spec#_165) is doing just that, as well as [Homebrew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mpich.rb#L63-L72).

**Comment by MarDiehl** [comment]
> @MarDiehl Could you please set `FCFLAGS` and `FFLAGS` in the configure invocation as I instructed before?. You may need these flags in all cases, otherwise the `mpifort` compiler wrapper may be unusable to compile Fortran MPI programs. Look like [Fedora](https://src.fedoraproject.org/rpms/mpich/blob/rawhide/f/mpich.spec#_165) is doing just that, as well as [Homebrew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mpich.rb#L63-L72).

Ok, I tried to avoid it because the gcc developer strongly discourage this option.

**Comment by dalcinl** [comment]
> Ok, I tried to avoid it because the gcc developer strongly discourage this option.

Yes, I know, but we are left with no alternative... Unless we run `sed` on the installed files to remove the flag.

@hzhou This `-fallow-argument-mismatch` to `gfortran` is a bit annoying. There has been any proposal or attempt to handle it automatically within MPICH's configure? 

BTW, running
```shell
./configure MPICHLIB_FFLAGS=-fallow-argument-mismatch MPICHLIB_FCFLAGS=-fallow-argument-mismatch
```
within a fresh unpack of the 4.0 tarball, it fails with the usual `-fallow-argument-mismatch` admonition.
How can we set the flags for the library but NOT for the compiler wrappers, as MPICH's README teach us?

**Comment by hzhou** [comment]
> > Ok, I tried to avoid it because the gcc developer strongly discourage this option.
> 

We understand this and agree, That is the reason we choose to error out in configure so the user will be conscious about adding this flag. 

> Yes, I know, but we are left with no alternative... Unless we run `sed` on the installed files to remove the flag.
> 
> @hzhou This `-fallow-argument-mismatch` to `gfortran` is a bit annoying. There has been any proposal or attempt to handle it automatically within MPICH's configure?
> 

We have revamped the Fortran binding in the current main branch, so the 4.1 release (end of this year) will not need this flag. To be precise, we will automatically add this flag to `mpif77` and omit this flag for `mpifort`. 

As of now, if `mpifort` does not contain this flag, it will not be able to compile most Fortran MPI programs with the newer GCC. It is not needed for compiling MPICH itself. It is needed for the wrapper script.

> BTW, running
> 
> ```shell
> ./configure MPICHLIB_FFLAGS=-fallow-argument-mismatch MPICHLIB_FCFLAGS=-fallow-argument-mismatch
> ```
> 
> within a fresh unpack of the 4.0 tarball, it fails with the usual `-fallow-argument-mismatch` admonition. How can we set the flags for the library but NOT for the compiler wrappers, as MPICH's README teach us?

There are two places that check for this flag. The above configure line should work for the main MPICH configure, which recognizes `MPICHLIB_xFLAGS`. The failure is from testsuite configure in `test/mpi`. Without the `F77_FLAGS` and `FC_FLAGS`, the Fortran tests are not going to compile.

**Comment by dalcinl** [comment]
@conda-forge-admin please rerender

**Comment by dalcinl** [comment]
@hzhou Thanks for your input. After adding `-fallow-argument-mismatch`, we still have some troubles. Not idea whether it is an issue within MPICH configure, or a conda-forge's build environment issue.

**Comment by MarDiehl** [comment]
> @hzhou Thanks for your input. After adding `-fallow-argument-mismatch`, we still have some troubles. Not idea whether it is an issue within MPICH configure, or a conda-forge's build environment issue.

did you try setting F77_FLAGS and FC_FLAGS?

**Comment by MarDiehl** [comment]
the current error message is
```
2022-02-22T08:13:55.0383270Z checking for Fortran 77 libraries of x86_64-apple-darwin13.4.0-gfortran... 
2022-02-22T08:13:55.0818770Z checking whether x86_64-apple-darwin13.4.0-gfortran accepts the FLIBS found by autoconf... no
2022-02-22T08:13:55.0820080Z checking for valid entries in FLIBS... 
2022-02-22T08:13:55.2157630Z checking whether x86_64-apple-darwin13.4.0-clang links with FLIBS found by autoconf... yes
2022-02-22T08:13:55.4493530Z checking whether Fortran 77 and C objects are compatible... no
2022-02-22T08:13:55.4578060Z checking for file... file
2022-02-22T08:13:55.4918710Z configure: error: ****  Incompatible Fortran and C Object File Types!  ****
```

I just guessing, but I would be surprised if that is related to `-fallow-argument-mismatch`.

**Comment by hzhou** [comment]
> the current error message is
> 
> ```
> 2022-02-22T08:13:55.0383270Z checking for Fortran 77 libraries of x86_64-apple-darwin13.4.0-gfortran... 
> 2022-02-22T08:13:55.0818770Z checking whether x86_64-apple-darwin13.4.0-gfortran accepts the FLIBS found by autoconf... no
> 2022-02-22T08:13:55.0820080Z checking for valid entries in FLIBS... 
> 2022-02-22T08:13:55.2157630Z checking whether x86_64-apple-darwin13.4.0-clang links with FLIBS found by autoconf... yes
> 2022-02-22T08:13:55.4493530Z checking whether Fortran 77 and C objects are compatible... no
> 2022-02-22T08:13:55.4578060Z checking for file... file
> 2022-02-22T08:13:55.4918710Z configure: error: ****  Incompatible Fortran and C Object File Types!  ****
> ```
> 
> I just guessing, but I would be surprised if that is related to `-fallow-argument-mismatch`.

This might be due to this issue: https://github.com/pmodels/mpich/issues/5768. `clang` with `-O2` decided no to produce PIE objects, and gfortran require PIE objects to link. This patch https://github.com/pmodels/mpich/pull/5771 works around it.

**Comment by dalcinl** [comment]
Well, looks like the patch does not work out of the box with the release tarball. I guess we should wait until next patch release tarball is out.

**Comment by dalcinl** [comment]
I tried adding `-fPIC` to `{C|CXX|F|FC}FLAGS`, and it did not work. I've run out of ideas.

**Comment by hzhou** [comment]
> I tried adding `-fPIC` to `{C|CXX|F|FC}FLAGS`, and it did not work. I've run out of ideas.

Could you upload the `config.log`?

**Comment by dalcinl** [comment]
Closed in favor of #68.

**Pull request closed without merging**
