### PR TITLE
Update/4.1.1

### PR DESCRIPTION
**Pull request by dalcinl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dalcinl** [comment]
In this PR, I'm proposing to switch to the new CH4 device implementation (`./configure --with-device=ch4`). I'm not sure this is a smart move though. Other Linux distributions have not done the switch just yet, I don't know whether that is an oversight or a backward compatibility decision.

**Comment by dalcinl** [comment]
@isuruf I could not manage to figure out why the bot cannot handle the recipe migration. You pointed out to the following errors in Gitter, but I don't quite get where the problem is. Therefore, I'm doing a manual update.

```
The recipe did not change in the version migration, a URL did not hash, or there is jinja2 syntax the bot cannot handle!

Please check the URLs in your recipe with version '4.1.1' to make sure they exist!

We also found the following errors:

 - missing jinja2 variable 'version_url' for selector 'None'
 - could not hash URL template 'http://www.mpich.org/static/downloads/{{ version_url }}/mpich-{{ version_url }}.tar.gz'
```

**Comment by dalcinl** [comment]
@hzhou The binary packages we build here are intended for mass consumption of possibly inexperienced users. Any reasons to stick the old ch3 instead of switching to the new ch4?

**Comment by hzhou** [comment]
> @hzhou The binary packages we build here are intended for mass consumption of possibly inexperienced users. Any reasons to stick the old ch3 instead of switching to the new ch4?

No. We recommend using ch4 unless the target system is too old/odd and ch4 does not build.

**Comment by leofang** [comment]
@dalcinl Just use a higher macOS SDK to compile, and don't touch the deployment target, see the docs here: https://conda-forge.org/docs/maintainer/knowledge_base.html#requiring-newer-macos-sdks
I think the recent change of the CI runner image exposes this need further.

**Comment by dalcinl** [comment]
@leofang From the section you linked (emphasis mine): 

> _While the default version 10.9 can be overridden using the following changes to the recipe, **it should be done as a last resort**. **Please consult with core team if this is something you think you need.**_. 

So I'm asking the core conda-forge team what to do :face_with_spiral_eyes:.

Additionally, as you can see from the patch added in my last commit, I managed to add a backward compatibility fix. However, I'm not really sure about the convenience of it.

**Comment by leofang** [comment]
I just noticed you already linked to the same doc. Note the text immediately follows:
> Note that this should be done if the error you are getting says that a header is not found or a macro is not defined.

which is precisely the situation here. 

It's great that you manage to patch it, we can merge as is, but using a newer SDK would be easier for future occurrences like this.

**Comment by dalcinl** [comment]
New error:
```
src/mem.c:112:25: error: use of undeclared identifier '_SC_PHYS_PAGES'
        page_cnt = ofi_sysconf(_SC_PHYS_PAGES);
```
I'll try bumping the SDK version.

**Comment by leofang** [comment]
We've seen this error before, but we didn't try this suggestion:
https://stackoverflow.com/questions/30511579/linux-sc-phys-pages-not-working-on-mac-os-x

**Comment by dalcinl** [comment]
@leofang Travis-CI ppc64le fails to build within the allowed time. What should we do? Just forget about it?

**Comment by leofang** [comment]
@dalcinl Usually we'd start by bumping this to say 120 mins:
https://conda-forge.org/docs/maintainer/conda_forge_yml.html#idle-timeout-minutes
but it's not always working...

**Comment by dalcinl** [comment]
@leofang The 50 min time is a Travis-CI hard limit for public repos, and we are hitting it. Should we switch to some other provider, e.g. Azure Pipelines?

**Comment by leofang** [comment]
Ah OK, right it was cut not because the CI was too quiet in the first 10 mins, but because of hitting 50 mins. In this case, we have 3 options:
1. Retry on main until success
2. Switch to Azure and cross-compile
3. Switch to Azure and use QEMU

**Comment by dalcinl** [comment]
@leofang The Azure+QEMU option did not work, it takes more than the max allowed 6 hours to run. 

About the cross-compile path, I never did it, I have not idea how to do it, and it may take more time than the one I'm willing to spend on it. I think I'll just disable ppc64le and merge this PR. Anyone who cares about ppc64le is most welcome to contribute the required recipe updates at a later time.

**Comment by leofang** [comment]
Sure sounds good to me. I've been tracking ppc64le download counts in various projects lately, and I do also suspect no one is using, and yet we are often blocked by ppc64le support...

That said, @jakirkham suggestion on the openmpi side might be a solution for both problems: using ucx from conda-forge to 1. reduce build time (because mpich builds a copy of ucx if it doesn't find one), 2. support CUDA without expanding the build matrix. I can look into it later next week. The only blocker I see is the ucx CF package doesn't have osx support yet.

**Comment by leofang** [comment]
@hzhou, sorry to bug you again, would you mind updating us on the latest status of ch4:ucx? 
1. Does it support dynamic process management now? It used to be no (based on [this line](https://github.com/pmodels/mpich/blob/6201856161011d54092ae99028a50eac1cf78d04/RELEASE_NOTES#L8)), but I found you had [a PR](https://github.com/pmodels/mpich/pull/5465) merged a while ago to prepare for that.
2. Can we build CUDA-aware UCX, but do not pass --with-cuda when building MPICH, and still make it CUDA-aware (through UCX)?

We are hoping to use UCX as a proxy to solve long standing issues at once :) Thanks!

**Comment by dalcinl** [comment]
@isuruf I'll wait for your confirmation to merge.

**Comment by isuruf** [comment]
Ready to merge

**Pull request merged**
